# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_task', '0002_auto_20161219_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentpasswordentered',
            name='assignmentid',
            field=models.IntegerField(db_column='assignmentID', primary_key=True),
        ),
    ]
