# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
