# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peer_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField("CourseList", "stucode", models.CharField(max_length=128, null=True)),
        migrations.AddField("CourseList", "tascode", models.CharField(max_length=128, null=True)),
        migrations.AlterField("CourseList", "courseid", models.AutoField(db_column='courseID', primary_key=True, serialize=False)),
    ]
