# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0002_courseconfiguration_courselist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField(blank=True)),
                ('userid', models.IntegerField()),
                ('usertype', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'course_member',
            },
        ),
    ]
