# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0003_coursemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='markingload',
            field=models.FloatField(db_column='markingLoad', null=True),
        ),
    ]
