# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0004_coursemember_markingload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemember',
            name='markingload',
            field=models.FloatField(db_column='markingload', null=True),
        ),
    ]
