# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0005_auto_20161225_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfiguration',
            name='scorenoise',
            field=models.FloatField(db_column='scoreNoise'),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
