# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
    ]
